apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: app-ns
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cloudbook/c09-order-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: LINE_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://line-postgres/linedb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://line-postgres/linedb_order
