apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: app-ns
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
