apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/deployment.yml
  - ./resources/service.yml

configMapGenerator:
  - name: catalog-config
    files:
      - ./resources/application.yml
    options:
      labels:
        app: catalog-service
